-- ---------------------------------------------------------------- --
-- |     MAP - Mumb1e Admin Plugin   |   http://www.mumb1e.de/    | --    
-- |              ___      ___   _________   _________            | --
-- |             |   \    /   | |   ___   | |   ___   |           | --
-- |             |    \__/    | |  |   |  | |  |   |  |           | --
-- |             |  |\    /|  | |  |___|  | |  |___|  |           | --
-- |             |  | \__/ |  | |   ___   | |   ______|           | --
-- |             |  |      |  | |  |   |  | |  |                  | --
-- |             |__|      |__| |__|   |__| |__|                  | --
-- |                                                              | --
-- | --- VERSION ---                                              | --
-- | Build: 6194                                                  | --
-- | Version: V2.5.2                                              | --
-- | Date: 2013-02-24                                             | --
-- | --- COPYRIGHT ---                                            | --
-- | Build by P.M. and M.H. | Accept the Copyrights!              | --
-- | © by Michael Koch 'aka' P.M. <pm@mumb1e.de>                  | --
-- | --- LICENSE ---                                              | --
-- | MAP - Mumb1e Admin Plugin is a dual-licensed software        | --
-- | MAP is released for private end-users under GPLv3            | --
-- |   >>  (visit at: http://www.gnu.org/licenses/gpl-3.0.html)   | --
-- | MAP is released for commercial use under a commerial license | --
-- |   >>  (visit at: http://www.mumb1e.de/en/about/license)      | --
-- | --- ATTENTION ---                                            | --
-- | Changing, editing or spreading of this sourcecode in other   | --
-- | scripts, or on other websites only with permission by PM!    | --
-- ---------------------------------------------------------------- --

-- BEGINN NEW STATEMENT

CREATE TABLE IF NOT EXISTS `[database_prefix]channelviewer` (
  `server_id` int(11) NOT NULL,
  `colour` varchar(6) collate utf8_unicode_ci NOT NULL default 'ffffff',
  `font_colour` varchar(6) collate utf8_unicode_ci NOT NULL default '000000',
  `width` varchar(255) collate utf8_unicode_ci NOT NULL default '200',
  `height` varchar(255) collate utf8_unicode_ci NOT NULL default '500',
  `external_on` int(11) NOT NULL default '1',
  `safety_code` varchar(255) collate utf8_unicode_ci NOT NULL default 'Dx4dg6SG4fG5'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- BEGINN NEW STATEMENT

INSERT INTO `[database_prefix]channelviewer` (`server_id`, `colour`, `font_colour`, `width`, `height`, `external_on`, `safety_code`) VALUES
(1, 'FFFFFF', '000000', '200', '500', 1, 'Dx4dg6SG4fG5');

-- BEGINN NEW STATEMENT

CREATE TABLE IF NOT EXISTS `[database_prefix]email_content` (
  `content_id` int(9) NOT NULL AUTO_INCREMENT,
  `template_id` int(9) NOT NULL,
  `language` varchar(3) COLLATE utf8_unicode_ci NOT NULL,
  `type` varchar(10) COLLATE utf8_unicode_ci NOT NULL,
  `text` text COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`content_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='Übersetzte Texte' AUTO_INCREMENT=61 ;

-- BEGINN NEW STATEMENT

INSERT INTO `[database_prefix]email_content` (`content_id`, `template_id`, `language`, `type`, `text`) VALUES
(1, 14005, 'en', 'subject', 'You are sucessfully registered at {ServerName}!'),
(2, 14005, 'de', 'subject', 'Du wurdest soeben erfolgreich auf {ServerName} registriert!'),
(3, 14005, 'en', 'body', '<p>The Administrator {AdminName} of the Mumble Server {ServerName} has just created the following account:</p>\r\n<p>Servername: <strong>{ServerName}</strong></p>\r\n<p>Server IP: <strong>{ServerIP}</strong></p>\r\n<p>Server Port: <strong>{ServerPort}</strong></p>\r\n<p>Your new Username: <strong>{UserName}</strong></p>\r\n<p>Your new Password: <strong>{UserPassword}</strong></p>\r\n<p>See you on the server!</p>\r\n<p>{AdminName}</p>'),
(4, 14005, 'de', 'body', '<p>Soeben hat der Admin {AdminName} des Mumble-Servers {ServerName} folgendens Konto f&uuml;r dich erstellt:</p>\r\n<p>Servername: <strong>{ServerName}</strong></p>\r\n<p>Server IP: <strong>{ServerIP} </strong></p>\r\n<p>Server Port: <strong>{ServerPort} </strong></p>\r\n<p>Dein neuer Username: <strong>{UserName} </strong></p>\r\n<p>Dein neues Passwort: <strong>{UserPassword}</strong></p>\r\n<p>Bis bald auf dem Server!</p>\r\n<p>{AdminName}</p>'),
(5, 17001, 'en', 'subject', 'Your account has been successfully created!'),
(6, 17001, 'de', 'subject', 'Dein Admin-Konto wurde erstellt!'),
(7, 17001, 'en', 'body', '<p>The Administrator {ResellerName} of the Mumb1e Admin Plugin {URL} has created the following account:</p>\r\n<p>Your new MAP-Account:</p>\r\n<p>Login: {AdminLogin}</p>\r\n<p>Password: {AdminPassword}</p>'),
(8, 17001, 'de', 'body', '<p>Soeben hat der Admin {ResellerName} des Mumb1e Admin Plugins auf <a>{URL} </a>folgenden Account f&uuml;r dich erstellt:</p>\r\n<p>Dein neues MAP-Konto:</p>\r\n<p>Login: {AdminLogin}</p>\r\n<p>Passwort: {AdminPassword}</p>'),
(9, 19001, 'en', 'subject', 'Your account has just been submitted!'),
(10, 19001, 'de', 'subject', 'Dein Konto wurde erfolgreich beantragt!'),
(11, 19001, 'en', 'body', '<p>You have successfully submitted your account! An admin will now take care of the activation! When your account is activated, you will automatically receive a confirmation e-mail!</p>\r\n<p>Review of the submitted account request:</p>\r\n<p>Username: {UserName}</p>\r\n<p>Server: {ServerName}</p>\r\n<p>Password: {Password}</p>\r\n<p>If a field is incorrect, or any other problem occurred, please notify the administrator!</p>\r\n<p>Best regards, The Administrator</p>'),
(12, 19001, 'de', 'body', '<p>Du hast deinen Account erfolgreich beantragt! Ein Admin wird sich jetzt um die Freischaltung k&uuml;mmern! Wenn dein Konto freigeschaltet wurde, erh&auml;llst du automatisch eine Best&auml;tigungs-E-Mail!</p>\r\n<p>Zur &Uuml;bersicht hier noch mal deine beantragten Daten:</p>\r\n<p>Benutzername: {UserName}</p>\r\n<p>Server:{ServerName}</p>\r\n<p>Passwort: {Password}</p>\r\n<p>Sollte eine Eingabe falsch sein, oder ein anderes Problem aufgetreten sein, wende dich bitte an den Administrator!</p>\r\n<p>Alles Gute, der Administrator</p>'),
(13, 19002, 'en', 'subject', 'Account has been requested: {UserName}'),
(14, 19002, 'de', 'subject', 'Account wurde beantragt: {UserName} '),
(15, 19002, 'en', 'body', '<p>A User has just submitted an Account Request.<br />Please go on MAP to unlock the Accounts.</p>\r\n<p>Link: {ServerURL}</p>\r\n<p>Thanks a lot,<br /> the MAP Autoscript</p>'),
(16, 19002, 'de', 'body', '<p>Soeben hat ein User einen Account beantragt. Gehe zum MAP um das Konto freizuschalten.</p>\r\n<p>Link: {ServerURL}</p>\r\n<p>Vielen Dank, das MAP Autoscript</p>'),
(17, 19003, 'en', 'subject', 'Your account has not been activated!'),
(18, 19003, 'de', 'subject', 'Dein Konto wurde nicht freigegeben und gelöscht!'),
(19, 19003, 'en', 'body', '<p>Hello,</p>\r\n<p>the submitted account <strong>{UserName}</strong> at <strong>{RequestTime}</strong> was looked by the Admin&nbsp;<strong>{AdminName}</strong> and rejected!</p>\r\n<p>Reason: <strong>{Reason}</strong>&nbsp;</p>\r\n<p>Thank you for your inquiry, {AdminName}</p>'),
(20, 19003, 'de', 'body', '<p>Hallo,</p>\r\n<p>dein von dir beantragtes Konto <strong>{UserName}</strong> am <strong>{RequestTime}</strong> wurde gerade von dem Admin<strong> {AdminName} </strong>abgelehnt!</p>\r\n<p>Grund<strong>: {Reason}</strong></p>\r\n<p>Vielen Dank f&uuml;r deine Anfrage, {AdminName}</p>'),
(21, 19004, 'en', 'subject', 'Your account for {ServerName} has been activated!'),
(22, 19004, 'de', 'subject', 'Dein Konto für {ServerName} wurde freigeschaltet!'),
(23, 19004, 'en', 'body', '<p>The Administrator {AdminName} of the Mumble Server {ServerName} has just created the following account:</p>\r\n<p>Servername: <strong>{ServerName}</strong></p>\r\n<p>Server IP: <strong>{ServerIP}</strong></p>\r\n<p>Server Port: <strong>{ServerPort}</strong></p>\r\n<p>Your new Username: <strong>{UserName}</strong></p>\r\n<p>Your new Password: <strong>{UserPassword}</strong></p>\r\n<p>See you on the server!</p>\r\n<p>{AdminName}</p>'),
(24, 19004, 'de', 'body', '<p>Soeben hat der Admin {AdminName} des Mumble-Servers {ServerName} folgendens Konto f&uuml;r dich erstellt:</p>\r\n<p>Servername: <strong>{ServerName}</strong></p>\r\n<p>Server IP: <strong>{ServerIP} </strong></p>\r\n<p>Server Port: <strong>{ServerPort} </strong></p>\r\n<p>Dein neuer Username: <strong>{UserName} </strong></p>\r\n<p>Dein neues Passwort: <strong>{UserPassword}</strong></p>\r\n<p>Bis bald auf dem Server!</p>\r\n<p>{AdminName}</p>'),
(25, 19005, 'en', 'subject', 'Your account for {ServerName}  has been activated!'),
(26, 19005, 'de', 'subject', 'Dein Account für {ServerName}  wurde freigeschaltet!'),
(27, 19005, 'en', 'body', '<p>The Admin {AdminName} of the Mumb1e Admin Plugin of {MAPURL} has just activated your account. Please find your login information here :</p>\r\n<p>Your MAP-Account: <strong>{UserName}</strong></p>\r\n<p>Your Password: <strong>{UserPassword} </strong></p>\r\n<p>See you on Mumb1e Admin Plugin!</p>\r\n<p>{AdminName}</p>'),
(28, 19005, 'de', 'body', '<p>Soeben hat der Admin {AdminName} des Mumb1e Admin Plugins auf {MAPURL} deinen beantragten Account freigeschaltet. Mit den folgenden Daten kannst du dich jetzt einloggen:</p>\r\n<p>Dein MAP-Konto: <strong>{UserName} </strong></p>\r\n<p>Dein Passwort: <strong>{UserPassword} </strong></p>\r\n<p>Viel Spass mit dem Mumb1e Admin Plugin!</p>\r\n<p>{AdminName}</p>'),
(29, 23001, 'en', 'subject', 'Mumble Server: Reset your password'),
(30, 23001, 'de', 'subject', 'Mumble Server: Zurücksetzen Ihres Passwortes'),
(31, 23001, 'en', 'body', '<p>Hello,</p>\r\n<p>you have just started the try, to reset the password of your Mumble server. Below you see this e-mail was sent with the confirmation link. Please, click now on the following link:</p>\r\n<p><span style="text-decoration: underline;"><strong>{Backlink}</strong></span></p>\r\n<p>You will be redirected to the page where you can put your new password.</p>'),
(32, 23001, 'de', 'body', '<p>Guten Tag,</p>\r\n<p>sie haben soeben den Versuch gestartet, Ihr Passwort f&uuml;r Ihren Mumble Server zur&uuml;ckzusetzten. Im folgenden wurde Ihnen diese E-Mail mit dem Best&auml;tigungslink gesendet. Klicken Sie bitte nun auf dem folgenden Link:</p>\r\n<p><span style="text-decoration: underline;"><strong>{Backlink}</strong></span></p>\r\n<p>Sie werden nun auf die Seite geleitet, auf der Sie Ihr Passwort neu setzen k&ouml;nnen.</p>'),
(33, 23002, 'en', 'subject', 'Reset your password'),
(34, 23002, 'de', 'subject', 'Zurücksetzen Ihres Passwortes'),
(35, 23002, 'en', 'body', '<p>Good day,</p>\r\n<p>you have just started the try, to reset the password of your MAP account. Below you see this e-mail was sent with the confirmation link. Please, click now on the following link:</p>\r\n<p><span style="text-decoration: underline;"><strong>{Backlink}</strong></span></p>\r\n<p>You will be redirected to the page where you can put your new password.</p>\r\n<p>&nbsp;</p>'),
(36, 23002, 'de', 'body', '<p>Guten Tag,</p>\r\n<p>sie haben soeben den Versuch gestartet, Ihr Passwort f&uuml;r das MAP zur&uuml;ckzusetzten. Im folgenden wurde Ihnen diese E-Mail mit dem Best&auml;tigungslink gesendet. Klicken Sie bitte nun auf dem folgenden Link:</p>\r\n<p><span style="text-decoration: underline;"><strong>{Backlink}</strong></span></p>\r\n<p>Sie werden nun auf die Seite geleitet, auf der Sie Ihr Passwort neu setzen k&ouml;nnen.</p>'),
(37, 23003, 'en', 'subject', 'Mumble Server: Your User Name'),
(38, 23003, 'de', 'subject', 'Mumble Server: Ihr Benutzername'),
(39, 23003, 'en', 'body', '<p>Hello,</p>\r\n<p>you have just requested your user name by e-mail!</p>\r\n<p>Your user name is: {UserName}</p>'),
(40, 23003, 'de', 'body', '<p>Guten Tag,</p>\r\n<p>Sie haben soeben Ihren Benutzernamen per E-Mail angefordert.</p>\r\n<p>Ihr Benutzername lautet: {UserName}</p>'),
(41, 23004, 'en', 'subject', 'Your MAP-Login'),
(42, 23004, 'de', 'subject', 'Ihr MAP-Benutzername'),
(43, 23004, 'en', 'body', '<p>Hello,</p>\r\n<p>you have just requested your loginame by e-mail!</p>\r\n<p>Your MAP-Loginname is: {AdminName}</p>'),
(44, 23004, 'de', 'body', '<p>Guten Tag,</p>\r\n<p>Sie haben soeben Ihren Benutzernamen per E-Mail angefordert.</p>\r\n<p>Ihr Benutzername lautet: {AdminName}</p>'),
(45, 35010, 'en', 'subject', 'Info-Mail: {Subject}'),
(46, 35010, 'de', 'subject', 'Info-Mail: {Subject}'),
(47, 35010, 'en', 'body', '<p>The Admin {AdminName} has send a you a new message with MAP:</p>\r\n<p>-----------------------------------</p>\r\n<p>{Body}</p>'),
(48, 35010, 'de', 'body', '<p>Der Admin {AdminName} hat dir soeben die folgende Nachricht &uuml;ber das MAP gesendet:</p>\r\n<p>-----------------------------------</p>\r\n<p>{Body}</p>'),
(49, 35011, 'en', 'subject', 'Info-Mail: {Subject}'),
(50, 35011, 'de', 'subject', 'Info-Mail: {Subject}'),
(51, 35011, 'en', 'body', '<p>The Admin {AdminName} has send a you a new message with MAP:</p>\r\n<p>-----------------------------------</p>\r\n<p>{Body}</p>'),
(52, 35011, 'de', 'body', '<p>Der Admin {AdminName} hat dir soeben die folgende Nachricht &uuml;ber das MAP gesendet:</p>\r\n<p>-----------------------------------</p>\r\n<p>{Body}</p>'),
(53, 35012, 'en', 'subject', 'Info-Mail: {Subject}'),
(54, 35012, 'de', 'subject', 'Info-Mail: {Subject}'),
(55, 35012, 'en', 'body', '<p>The Admin {AdminName} has send a you a new message with MAP:</p>\r\n<p>-----------------------------------</p>\r\n<p>{Body}</p>'),
(56, 35012, 'de', 'body', '<p>Der Admin {AdminName} hat dir soeben die folgende Nachricht &uuml;ber das MAP gesendet:</p>\r\n<p>-----------------------------------</p>\r\n<p>{Body}</p>'),
(57, 93001, 'en', 'subject', 'Test E-Mail'),
(58, 93001, 'de', 'subject', 'Test E-Mail'),
(59, 93001, 'en', 'body', '<p>This is a test mail. This mail was initiated by {ResellerName} at {Date}. Looks like your settings work!</p>'),
(60, 93001, 'de', 'body', '<p>Dies ist eine Test-Mail. Sie wurde soeben durch {ResellerName} um {Date} ausgel&ouml;st. Scheinbar funktionieren deine Einstellungen!</p>');

-- BEGINN NEW STATEMENT

CREATE TABLE IF NOT EXISTS `[database_prefix]email_history` (
  `email_id` int(9) NOT NULL AUTO_INCREMENT,
  `template_id` int(9) NOT NULL,
  `subject` text CHARACTER SET utf8 NOT NULL,
  `text` text COLLATE utf8_unicode_ci NOT NULL,
  `to_mail` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `to_name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `to_user_id` varchar(9) COLLATE utf8_unicode_ci NOT NULL,
  `from_mail` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `from_name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `from_user_id` varchar(9) COLLATE utf8_unicode_ci NOT NULL,
  `counter` int(9) NOT NULL,
  `last_sent` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`email_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='gesendete E-Mail History des MAP' AUTO_INCREMENT=1 ;

-- BEGINN NEW STATEMENT

CREATE TABLE IF NOT EXISTS `[database_prefix]email_placeholder` (
  `placeholder_id` int(9) NOT NULL AUTO_INCREMENT,
  `template_id` int(9) NOT NULL,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `translation_name` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '_email_placeholder_name_',
  `translation_discription` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '_email_placeholder_disc_',
  PRIMARY KEY (`placeholder_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='Platzhalter, für Content in E-Mails' AUTO_INCREMENT=47 ;

-- BEGINN NEW STATEMENT

INSERT INTO `[database_prefix]email_placeholder` (`placeholder_id`, `template_id`, `name`, `translation_name`, `translation_discription`) VALUES
(1, 14005, 'ServerName', '_email_placeholder_name_14005_ServerName', '_email_placeholder_disc_14005_ServerName'),
(2, 14005, 'ServerIP', '_email_placeholder_name_14005_ServerIP', '_email_placeholder_disc_14005_ServerIP'),
(3, 14005, 'ServerPort', '_email_placeholder_name_14005_ServerPort', '_email_placeholder_disc_14005_ServerPort'),
(4, 14005, 'UserName', '_email_placeholder_name_14005_UserName', '_email_placeholder_disc_14005_UserName'),
(5, 14005, 'UserPassword', '_email_placeholder_name_14005_UserPassword', '_email_placeholder_disc_14005_UserPassword'),
(6, 14005, 'UserEMail', '_email_placeholder_name_14005_UserEMail', '_email_placeholder_disc_14005_UserEMail'),
(7, 14005, 'AdminName', '_email_placeholder_name_14005_AdminName', '_email_placeholder_disc_14005_AdminName'),
(8, 17001, 'ResellerName', '_email_placeholder_name_17001_ResellerName', '_email_placeholder_disc_17001_ResellerName'),
(9, 17001, 'URL', '_email_placeholder_name_17001_URL', '_email_placeholder_disc_17001_URL'),
(10, 17001, 'AdminLogin', '_email_placeholder_name_17001_AdminLogin', '_email_placeholder_disc_17001_AdminLogin'),
(11, 17001, 'AdminPassword', '_email_placeholder_name_17001_AdminPassword', '_email_placeholder_disc_17001_AdminPassword'),
(12, 19001, 'UserName', '_email_placeholder_name_19001_UserName', '_email_placeholder_disc_19001_UserName'),
(13, 19001, 'ServerName', '_email_placeholder_name_19001_ServerName', '_email_placeholder_disc_19001_ServerName'),
(14, 19001, 'Password', '_email_placeholder_name_19001_Password', '_email_placeholder_disc_19001_Password'),
(15, 19002, 'UserName', '_email_placeholder_name_19002_UserName', '_email_placeholder_disc_19002_UserName'),
(16, 19002, 'ServerURL', '_email_placeholder_name_19002_ServerURL', '_email_placeholder_disc_19002_ServerURL'),
(17, 19003, 'UserName', '_email_placeholder_name_19003_UserName', '_email_placeholder_disc_19003_UserName'),
(18, 19003, 'RequestTime', '_email_placeholder_name_19003_RequestTime', '_email_placeholder_disc_19003_RequestTime'),
(19, 19003, 'Reason', '_email_placeholder_name_19003_Reason', '_email_placeholder_disc_19003_Reason'),
(20, 19003, 'AdminName', '_email_placeholder_name_19003_AdminName', '_email_placeholder_disc_19003_AdminName'),
(21, 19004, 'ServerName', '_email_placeholder_name_19004_ServerName', '_email_placeholder_disc_19004_ServerName'),
(22, 19004, 'ServerIP', '_email_placeholder_name_19004_ServerIP', '_email_placeholder_disc_19004_ServerIP'),
(23, 19004, 'ServerPort', '_email_placeholder_name_19004_ServerPort', '_email_placeholder_disc_19004_ServerPort'),
(24, 19004, 'UserName', '_email_placeholder_name_19004_UserName', '_email_placeholder_disc_19004_UserName'),
(25, 19004, 'UserPassword', '_email_placeholder_name_19004_UserPassword', '_email_placeholder_disc_19004_UserPassword'),
(26, 19004, 'AdminName', '_email_placeholder_name_19004_AdminName', '_email_placeholder_disc_19004_AdminName'),
(27, 19005, 'ServerName', '_email_placeholder_name_19005_ServerName', '_email_placeholder_disc_19005_ServerName'),
(28, 19005, 'MAPURL', '_email_placeholder_name_19005_MAPURL', '_email_placeholder_disc_19005_MAPURL'),
(29, 19005, 'UserName', '_email_placeholder_name_19005_UserName', '_email_placeholder_disc_19005_UserName'),
(30, 19005, 'UserPassword', '_email_placeholder_name_19005_UserPassword', '_email_placeholder_disc_19005_UserPassword'),
(31, 19005, 'AdminName', '_email_placeholder_name_19005_AdminName', '_email_placeholder_disc_19005_AdminName'),
(32, 23001, 'Backlink', '_email_placeholder_name_23001_Backlink', '_email_placeholder_disc_23001_Backlink'),
(33, 23002, 'Backlink', '_email_placeholder_name_23002_Backlink', '_email_placeholder_disc_23002_Backlink'),
(34, 23003, 'UserName', '_email_placeholder_name_23003_UserName', '_email_placeholder_disc_23003_UserName'),
(35, 23004, 'AdminName', '_email_placeholder_name_23004_AdminName', '_email_placeholder_disc_23004_AdminName'),
(36, 35010, 'Subject', '_email_placeholder_name_35010_Subject', '_email_placeholder_disc_35010_Subject'),
(37, 35010, 'Body', '_email_placeholder_name_35010_Body', '_email_placeholder_disc_35010_Body'),
(38, 35010, 'AdminName', '_email_placeholder_name_35010_AdminName', '_email_placeholder_disc_35010_AdminName'),
(39, 35011, 'Subject', '_email_placeholder_name_35011_Subject', '_email_placeholder_disc_35011_Subject'),
(40, 35011, 'Body', '_email_placeholder_name_35011_Body', '_email_placeholder_disc_35011_Body'),
(41, 35011, 'AdminName', '_email_placeholder_name_35011_AdminName', '_email_placeholder_disc_35011_AdminName'),
(42, 35012, 'Subject', '_email_placeholder_name_35012_Subject', '_email_placeholder_disc_35012_Subject'),
(43, 35012, 'Body', '_email_placeholder_name_35012_Body', '_email_placeholder_disc_35012_Body'),
(44, 35012, 'AdminName', '_email_placeholder_name_35012_AdminName', '_email_placeholder_disc_35012_AdminName'),
(45, 93001, 'Date', '_email_placeholder_name_93001_date', '_email_placeholder_disc_93001_date'),
(46, 93001, 'ResellerName', '_email_placeholder_name_93001_resellername', '_email_placeholder_disc_93001_resellername');

-- BEGINN NEW STATEMENT

CREATE TABLE IF NOT EXISTS `[database_prefix]email_templates` (
  `template_id` int(9) NOT NULL,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `lock` int(9) NOT NULL,
  `user_id` int(9) NOT NULL,
  `date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`template_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='E-Mail Templates';

-- BEGINN NEW STATEMENT

INSERT INTO `[database_prefix]email_templates` (`template_id`, `name`, `lock`, `user_id`, `date`) VALUES
(14005, 'create_user', 1, 1, '[aktdate]'),
(17001, 'admin_create', 1, 1, '[aktdate]'),
(19001, 'request_account_user', 1, 1, '[aktdate]'),
(19002, 'request_account_admin', 1, 1, '[aktdate]'),
(19003, 'delete_account_db', 1, 1, '[aktdate]'),
(19004, 'activate_account_user', 1, 1, '[aktdate]'),
(19005, 'activate_account_admin', 1, 1, '[aktdate]'),
(23001, 'operate_server_pass', 1, 1, '[aktdate]'),
(23002, 'operate_admin_pass', 1, 1, '[aktdate]'),
(23003, 'operate_server_login', 1, 1, '[aktdate]'),
(23004, 'operate_admin_login', 1, 1, '[aktdate]'),
(35010, 'email_mass_user', 1, 1, '[aktdate]'),
(35011, 'email_mass_customer', 1, 1, '[aktdate]'),
(35012, 'email_mass_reseller', 1, 1, '[aktdate]'),
(93001, 'test_mail', 1, 1, '[aktdate]');

-- BEGINN NEW STATEMENT

CREATE TABLE IF NOT EXISTS `[database_prefix]group` (
  `group_id` varchar(9) collate utf8_unicode_ci NOT NULL,
  `name` varchar(255) collate utf8_unicode_ci NOT NULL,
  `discription` text collate utf8_unicode_ci NOT NULL,
  `user_id` int(9) NOT NULL,
  `date` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='Zuordung Gruppendaten';

-- BEGINN NEW STATEMENT

INSERT INTO `[database_prefix]group` (`group_id`, `name`, `discription`, `user_id`, `date`) VALUES
('5bS48ceDP', 'Administrator', '<p>This Group is the group for all Master Admins and grand with ALL permissions! Don&acute;t remove here your own permissions and don&acute;t set the "recursive permissions off, because this will remove your permissions! Better add a new group with lower permissions if you will need it!</p>', 1, '[aktdate]'),
('z08MJmSv4', 'Customer', '<p>This is a groups for customers of resellers. Define this permission group to your customers. Please attention, that this permissions are set to recursive, so the customers can&acute;t add more permissions to there accounts,as they don&acute;t have allready. They can&acute;t also not create users with more permissions, as the have granted itself, when they are defined to this group! This permissions group is set, that the users have enough permissions to edit there own servers, but cant cheat MAP! Try it, add a user to this group and login with this user!</p>', 1, '[aktdate]');

-- BEGINN NEW STATEMENT

CREATE TABLE IF NOT EXISTS `[database_prefix]group_perm` (
  `group_id` varchar(9) collate utf8_unicode_ci NOT NULL,
  `section_id` varchar(9) collate utf8_unicode_ci NOT NULL,
  `value` int(9) default NULL,
  `date` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='Definiere Berechtigungen der Gruppe';

-- BEGINN NEW STATEMENT

INSERT INTO `[database_prefix]group_perm` (`group_id`, `section_id`, `value`, `date`) VALUES
('5bS48ceDP', '10001', 1, '[aktdate]'),
('z08MJmSv4', '10001', 1, '[aktdate]'),
('5bS48ceDP', '10004', 1, '[aktdate]'),
('z08MJmSv4', '10004', 1, '[aktdate]'),
('5bS48ceDP', '10007', 1, '[aktdate]'),
('z08MJmSv4', '10007', 1, '[aktdate]'),
('5bS48ceDP', '10010', 1, '[aktdate]'),
('z08MJmSv4', '10010', 1, '[aktdate]'),
('5bS48ceDP', '10013', 1, '[aktdate]'),
('z08MJmSv4', '10013', 1, '[aktdate]'),
('5bS48ceDP', '10016', 1, '[aktdate]'),
('z08MJmSv4', '10016', 1, '[aktdate]'),
('5bS48ceDP', '10019', 1, '[aktdate]'),
('z08MJmSv4', '10019', 1, '[aktdate]'),
('5bS48ceDP', '10022', 1, '[aktdate]'),
('z08MJmSv4', '10022', 1, '[aktdate]'),
('5bS48ceDP', '10025', 1, '[aktdate]'),
('z08MJmSv4', '10025', 0, '[aktdate]'),
('5bS48ceDP', '10026', 1, '[aktdate]'),
('z08MJmSv4', '10026', 0, '[aktdate]'),
('5bS48ceDP', '10028', 1, '[aktdate]'),
('z08MJmSv4', '10028', 1, '[aktdate]'),
('5bS48ceDP', '10031', 1, '[aktdate]'),
('z08MJmSv4', '10031', 0, '[aktdate]'),
('5bS48ceDP', '10034', 1, '[aktdate]'),
('z08MJmSv4', '10034', 1, '[aktdate]'),
('5bS48ceDP', '11001', 1, '[aktdate]'),
('z08MJmSv4', '11001', 1, '[aktdate]'),
('5bS48ceDP', '11002', 1, '[aktdate]'),
('z08MJmSv4', '11002', 1, '[aktdate]'),
('5bS48ceDP', '11005', 1, '[aktdate]'),
('z08MJmSv4', '11005', 0, '[aktdate]'),
('5bS48ceDP', '11006', 1, '[aktdate]'),
('z08MJmSv4', '11006', 1, '[aktdate]'),
('5bS48ceDP', '11007', 1, '[aktdate]'),
('z08MJmSv4', '11007', 0, '[aktdate]'),
('5bS48ceDP', '11020', 1, '[aktdate]'),
('z08MJmSv4', '11020', 1, '[aktdate]'),
('5bS48ceDP', '11021', 1, '[aktdate]'),
('z08MJmSv4', '11021', 1, '[aktdate]'),
('5bS48ceDP', '11022', 1, '[aktdate]'),
('z08MJmSv4', '11022', 1, '[aktdate]'),
('5bS48ceDP', '12001', 1, '[aktdate]'),
('z08MJmSv4', '12001', 0, '[aktdate]'),
('5bS48ceDP', '12002', 1, '[aktdate]'),
('z08MJmSv4', '12002', 0, '[aktdate]'),
('5bS48ceDP', '12003', 1, '[aktdate]'),
('z08MJmSv4', '12003', 0, '[aktdate]'),
('5bS48ceDP', '12004', 1, '[aktdate]'),
('z08MJmSv4', '12004', 0, '[aktdate]'),
('5bS48ceDP', '12005', 1, '[aktdate]'),
('z08MJmSv4', '12005', 0, '[aktdate]'),
('5bS48ceDP', '12006', 1, '[aktdate]'),
('z08MJmSv4', '12006', 1, '[aktdate]'),
('5bS48ceDP', '12007', 1, '[aktdate]'),
('z08MJmSv4', '12007', 1, '[aktdate]'),
('5bS48ceDP', '12008', 1, '[aktdate]'),
('z08MJmSv4', '12008', 1, '[aktdate]'),
('5bS48ceDP', '12009', 1, '[aktdate]'),
('z08MJmSv4', '12009', 1, '[aktdate]'),
('5bS48ceDP', '12010', 1, '[aktdate]'),
('z08MJmSv4', '12010', 1, '[aktdate]'),
('5bS48ceDP', '12011', 1, '[aktdate]'),
('z08MJmSv4', '12011', 0, '[aktdate]'),
('5bS48ceDP', '12012', 1, '[aktdate]'),
('z08MJmSv4', '12012', 0, '[aktdate]'),
('5bS48ceDP', '12013', 1, '[aktdate]'),
('z08MJmSv4', '12013', 0, '[aktdate]'),
('5bS48ceDP', '12014', 1, '[aktdate]'),
('z08MJmSv4', '12014', 0, '[aktdate]'),
('5bS48ceDP', '12015', 1, '[aktdate]'),
('z08MJmSv4', '12015', 0, '[aktdate]'),
('5bS48ceDP', '12016', 1, '[aktdate]'),
('z08MJmSv4', '12016', 1, '[aktdate]'),
('5bS48ceDP', '12017', 1, '[aktdate]'),
('z08MJmSv4', '12017', 1, '[aktdate]'),
('5bS48ceDP', '12018', 1, '[aktdate]'),
('z08MJmSv4', '12018', 1, '[aktdate]'),
('5bS48ceDP', '12019', 1, '[aktdate]'),
('z08MJmSv4', '12019', 1, '[aktdate]'),
('5bS48ceDP', '12020', 1, '[aktdate]'),
('z08MJmSv4', '12020', 1, '[aktdate]'),
('5bS48ceDP', '12021', 1, '[aktdate]'),
('z08MJmSv4', '12021', 1, '[aktdate]'),
('5bS48ceDP', '12022', 1, '[aktdate]'),
('z08MJmSv4', '12022', 1, '[aktdate]'),
('5bS48ceDP', '12023', 1, '[aktdate]'),
('z08MJmSv4', '12023', 1, '[aktdate]'),
('5bS48ceDP', '12024', 1, '[aktdate]'),
('z08MJmSv4', '12024', 1, '[aktdate]'),
('5bS48ceDP', '12025', 1, '[aktdate]'),
('z08MJmSv4', '12025', 0, '[aktdate]'),
('5bS48ceDP', '12026', 1, '[aktdate]'),
('z08MJmSv4', '12026', 0, '[aktdate]'),
('5bS48ceDP', '12027', 1, '[aktdate]'),
('z08MJmSv4', '12027', 0, '[aktdate]'),
('5bS48ceDP', '12028', 1, '[aktdate]'),
('z08MJmSv4', '12028', 0, '[aktdate]'),
('5bS48ceDP', '12029', 1, '[aktdate]'),
('z08MJmSv4', '12029', 0, '[aktdate]'),
('5bS48ceDP', '12030', 1, '[aktdate]'),
('z08MJmSv4', '12030', 0, '[aktdate]'),
('5bS48ceDP', '12031', 1, '[aktdate]'),
('z08MJmSv4', '12031', 1, '[aktdate]'),
('5bS48ceDP', '12032', 1, '[aktdate]'),
('z08MJmSv4', '12032', 1, '[aktdate]'),
('5bS48ceDP', '12033', 1, '[aktdate]'),
('z08MJmSv4', '12033', 1, '[aktdate]'),
('5bS48ceDP', '12034', 1, '[aktdate]'),
('z08MJmSv4', '12034', 1, '[aktdate]'),
('5bS48ceDP', '12035', 1, '[aktdate]'),
('z08MJmSv4', '12035', 1, '[aktdate]'),
('5bS48ceDP', '12036', 1, '[aktdate]'),
('z08MJmSv4', '12036', 0, '[aktdate]'),
('5bS48ceDP', '12037', 1, '[aktdate]'),
('z08MJmSv4', '12037', 1, '[aktdate]'),
('5bS48ceDP', '13001', 1, '[aktdate]'),
('z08MJmSv4', '13001', 1, '[aktdate]'),
('5bS48ceDP', '13002', 1, '[aktdate]'),
('z08MJmSv4', '13002', 1, '[aktdate]'),
('5bS48ceDP', '13003', 1, '[aktdate]'),
('z08MJmSv4', '13003', 1, '[aktdate]'),
('5bS48ceDP', '13004', 1, '[aktdate]'),
('z08MJmSv4', '13004', 1, '[aktdate]'),
('5bS48ceDP', '14002', 1, '[aktdate]'),
('z08MJmSv4', '14002', 1, '[aktdate]'),
('5bS48ceDP', '14005', 1, '[aktdate]'),
('z08MJmSv4', '14005', 1, '[aktdate]'),
('5bS48ceDP', '14006', 1, '[aktdate]'),
('z08MJmSv4', '14006', 1, '[aktdate]'),
('5bS48ceDP', '14007', 1, '[aktdate]'),
('z08MJmSv4', '14007', 1, '[aktdate]'),
('5bS48ceDP', '14011', 1, '[aktdate]'),
('z08MJmSv4', '14011', 1, '[aktdate]'),
('5bS48ceDP', '14012', 1, '[aktdate]'),
('z08MJmSv4', '14012', 1, '[aktdate]'),
('5bS48ceDP', '14013', 1, '[aktdate]'),
('z08MJmSv4', '14013', 1, '[aktdate]'),
('5bS48ceDP', '14014', 1, '[aktdate]'),
('z08MJmSv4', '14014', 1, '[aktdate]'),
('5bS48ceDP', '17001', 1, '[aktdate]'),
('z08MJmSv4', '17001', 1, '[aktdate]'),
('5bS48ceDP', '17002', 1, '[aktdate]'),
('z08MJmSv4', '17002', 1, '[aktdate]'),
('5bS48ceDP', '17005', 1, '[aktdate]'),
('z08MJmSv4', '17005', 1, '[aktdate]'),
('5bS48ceDP', '17006', 1, '[aktdate]'),
('z08MJmSv4', '17006', 1, '[aktdate]'),
('5bS48ceDP', '17007', 1, '[aktdate]'),
('z08MJmSv4', '17007', 0, '[aktdate]'),
('5bS48ceDP', '17020', 1, '[aktdate]'),
('z08MJmSv4', '17020', 0, '[aktdate]'),
('5bS48ceDP', '17021', 1, '[aktdate]'),
('z08MJmSv4', '17021', 1, '[aktdate]'),
('5bS48ceDP', '18001', 1, '[aktdate]'),
('z08MJmSv4', '18001', 1, '[aktdate]'),
('5bS48ceDP', '18002', 1, '[aktdate]'),
('z08MJmSv4', '18002', 1, '[aktdate]'),
('5bS48ceDP', '18003', 1, '[aktdate]'),
('z08MJmSv4', '18003', 1, '[aktdate]'),
('5bS48ceDP', '18004', 1, '[aktdate]'),
('z08MJmSv4', '18004', 1, '[aktdate]'),
('5bS48ceDP', '18005', 1, '[aktdate]'),
('z08MJmSv4', '18005', 1, '[aktdate]'),
('5bS48ceDP', '18006', 1, '[aktdate]'),
('z08MJmSv4', '18006', 0, '[aktdate]'),
('5bS48ceDP', '18007', 1, '[aktdate]'),
('z08MJmSv4', '18007', 0, '[aktdate]'),
('5bS48ceDP', '18008', 1, '[aktdate]'),
('z08MJmSv4', '18008', 0, '[aktdate]'),
('5bS48ceDP', '18009', 1, '[aktdate]'),
('z08MJmSv4', '18009', 1, '[aktdate]'),
('5bS48ceDP', '18010', 1, '[aktdate]'),
('z08MJmSv4', '18010', 1, '[aktdate]'),
('5bS48ceDP', '18011', 1, '[aktdate]'),
('z08MJmSv4', '18011', 1, '[aktdate]'),
('5bS48ceDP', '18012', 1, '[aktdate]'),
('z08MJmSv4', '18012', 0, '[aktdate]'),
('5bS48ceDP', '18013', 1, '[aktdate]'),
('z08MJmSv4', '18013', 1, '[aktdate]'),
('5bS48ceDP', '18014', 1, '[aktdate]'),
('z08MJmSv4', '18014', 1, '[aktdate]'),
('5bS48ceDP', '18015', 1, '[aktdate]'),
('z08MJmSv4', '18015', 1, '[aktdate]'),
('5bS48ceDP', '18016', 1, '[aktdate]'),
('z08MJmSv4', '18016', 1, '[aktdate]'),
('5bS48ceDP', '18017', 1, '[aktdate]'),
('z08MJmSv4', '18017', 1, '[aktdate]'),
('5bS48ceDP', '18018', 1, '[aktdate]'),
('z08MJmSv4', '18018', 1, '[aktdate]'),
('5bS48ceDP', '18019', 1, '[aktdate]'),
('z08MJmSv4', '18019', 1, '[aktdate]'),
('5bS48ceDP', '19001', 1, '[aktdate]'),
('z08MJmSv4', '19001', 1, '[aktdate]'),
('5bS48ceDP', '19006', 1, '[aktdate]'),
('z08MJmSv4', '19006', 1, '[aktdate]'),
('5bS48ceDP', '19007', 1, '[aktdate]'),
('z08MJmSv4', '19007', 1, '[aktdate]'),
('5bS48ceDP', '19008', 1, '[aktdate]'),
('z08MJmSv4', '19008', 1, '[aktdate]'),
('5bS48ceDP', '20001', 1, '[aktdate]'),
('z08MJmSv4', '20001', 0, '[aktdate]'),
('5bS48ceDP', '20002', 1, '[aktdate]'),
('z08MJmSv4', '20002', 0, '[aktdate]'),
('5bS48ceDP', '20003', 1, '[aktdate]'),
('z08MJmSv4', '20003', 0, '[aktdate]'),
('5bS48ceDP', '20004', 1, '[aktdate]'),
('z08MJmSv4', '20004', 0, '[aktdate]'),
('5bS48ceDP', '25001', 1, '[aktdate]'),
('z08MJmSv4', '25001', 1, '[aktdate]'),
('5bS48ceDP', '25002', 1, '[aktdate]'),
('z08MJmSv4', '25002', 0, '[aktdate]'),
('5bS48ceDP', '25003', 1, '[aktdate]'),
('z08MJmSv4', '25003', 0, '[aktdate]'),
('5bS48ceDP', '25004', 1, '[aktdate]'),
('z08MJmSv4', '25004', 0, '[aktdate]'),
('5bS48ceDP', '25005', 1, '[aktdate]'),
('z08MJmSv4', '25005', 0, '[aktdate]'),
('5bS48ceDP', '25006', 0, '[aktdate]'),
('z08MJmSv4', '25006', 1, '[aktdate]'),
('5bS48ceDP', '25012', 1, '[aktdate]'),
('z08MJmSv4', '25012', 1, '[aktdate]'),
('5bS48ceDP', '25014', 1, '[aktdate]'),
('z08MJmSv4', '25014', 1, '[aktdate]'),
('5bS48ceDP', '35001', 1, '[aktdate]'),
('z08MJmSv4', '35001', 0, '[aktdate]'),
('5bS48ceDP', '35002', 1, '[aktdate]'),
('z08MJmSv4', '35002', 0, '[aktdate]'),
('5bS48ceDP', '35003', 1, '[aktdate]'),
('z08MJmSv4', '35003', 0, '[aktdate]'),
('5bS48ceDP', '35004', 1, '[aktdate]'),
('z08MJmSv4', '35004', 0, '[aktdate]'),
('5bS48ceDP', '35005', 1, '[aktdate]'),
('z08MJmSv4', '35005', 0, '[aktdate]'),
('5bS48ceDP', '35006', 1, '[aktdate]'),
('z08MJmSv4', '35006', 0, '[aktdate]'),
('5bS48ceDP', '35007', 1, '[aktdate]'),
('z08MJmSv4', '35007', 0, '[aktdate]'),
('5bS48ceDP', '35008', 1, '[aktdate]'),
('z08MJmSv4', '35008', 0, '[aktdate]'),
('5bS48ceDP', '35009', 1, '[aktdate]'),
('z08MJmSv4', '35009', 0, '[aktdate]'),
('5bS48ceDP', '35010', 1, '[aktdate]'),
('z08MJmSv4', '35010', 0, '[aktdate]'),
('5bS48ceDP', '35011', 1, '[aktdate]'),
('z08MJmSv4', '35011', 0, '[aktdate]'),
('5bS48ceDP', '35012', 1, '[aktdate]'),
('z08MJmSv4', '35012', 0, '[aktdate]'),
('5bS48ceDP', '93001', 1, '[aktdate]'),
('z08MJmSv4', '93001', 0, '[aktdate]'),
('5bS48ceDP', '93002', 1, '[aktdate]'),
('z08MJmSv4', '93002', 0, '[aktdate]'),
('5bS48ceDP', '93003', 1, '[aktdate]'),
('z08MJmSv4', '93003', 0, '[aktdate]'),
('5bS48ceDP', '93004', 1, '[aktdate]'),
('z08MJmSv4', '93004', 0, '[aktdate]'),
('5bS48ceDP', '93005', 1, '[aktdate]'),
('z08MJmSv4', '93005', 0, '[aktdate]'),
('5bS48ceDP', '93006', 1, '[aktdate]'),
('z08MJmSv4', '93006', 0, '[aktdate]'),
('5bS48ceDP', '93007', 1, '[aktdate]'),
('z08MJmSv4', '93007', 0, '[aktdate]'),
('5bS48ceDP', '93021', 1, '[aktdate]'),
('z08MJmSv4', '93021', 0, '[aktdate]'),
('5bS48ceDP', '93022', 1, '[aktdate]'),
('z08MJmSv4', '93022', 0, '[aktdate]'),
('5bS48ceDP', '93023', 1, '[aktdate]'),
('z08MJmSv4', '93023', 0, '[aktdate]'),
('5bS48ceDP', '93024', 1, '[aktdate]'),
('z08MJmSv4', '93024', 0, '[aktdate]'),
('5bS48ceDP', '93025', 1, '[aktdate]'),
('z08MJmSv4', '93025', 0, '[aktdate]'),
('5bS48ceDP', '93026', 1, '[aktdate]'),
('z08MJmSv4', '93026', 0, '[aktdate]');

-- BEGINN NEW STATEMENT

CREATE TABLE IF NOT EXISTS `[database_prefix]log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `priority` int(11) NOT NULL,
  `action_id` varchar(255) collate utf8_unicode_ci NOT NULL,
  `ip` varchar(15) collate utf8_unicode_ci NOT NULL default '1234567890',
  `date` timestamp NOT NULL default CURRENT_TIMESTAMP,
  `area` varchar(255) collate utf8_unicode_ci NOT NULL,
  `server_id` int(11) default NULL,
  `value_1` text collate utf8_unicode_ci,
  `value_2` text collate utf8_unicode_ci,
  `value_3` text collate utf8_unicode_ci,
  `value_4` text collate utf8_unicode_ci,
  `value_5` text collate utf8_unicode_ci,
  `value_6` text collate utf8_unicode_ci,
  `value_7` text collate utf8_unicode_ci,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

-- BEGINN NEW STATEMENT

CREATE TABLE IF NOT EXISTS `[database_prefix]operate_pwd` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `server_id` int(11) NOT NULL,
  `type` int(11) NOT NULL,
  `saftey_code` varchar(255) collate utf8_unicode_ci NOT NULL,
  `email` varchar(255) collate utf8_unicode_ci NOT NULL,
  `date` timestamp NOT NULL default CURRENT_TIMESTAMP,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

-- BEGINN NEW STATEMENT

CREATE TABLE IF NOT EXISTS `[database_prefix]request` (
  `id` int(9) NOT NULL AUTO_INCREMENT,
  `server_id` int(9) NOT NULL,
  `type` int(1) NOT NULL default '1',
  `name` varchar(255) collate utf8_unicode_ci NOT NULL,
  `email` varchar(255) collate utf8_unicode_ci NOT NULL,
  `pw` varchar(128) collate utf8_unicode_ci default NULL,
  `ip` varchar(15) collate utf8_unicode_ci NOT NULL,
  `request_time` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

-- BEGINN NEW STATEMENT

CREATE TABLE IF NOT EXISTS `[database_prefix]section` (
  `section_id` int(9) NOT NULL,
  `name` varchar(255) collate utf8_unicode_ci NOT NULL,
  `name_translation` varchar(255) collate utf8_unicode_ci NOT NULL default '_perm_name_',
  `discription` text collate utf8_unicode_ci NOT NULL,
  `discr_translation` varchar(255) collate utf8_unicode_ci NOT NULL default '_perm_disc_',
  `default_perms` int(9) NOT NULL default '1',
  `section_name` varchar(255) collate utf8_unicode_ci NOT NULL,
  `section_path` varchar(255) collate utf8_unicode_ci NOT NULL,
  `error_message` int(9) NOT NULL default '0',
  `data_count` int(9) NOT NULL default '0'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='Definiere Sections im MAP';

-- BEGINN NEW STATEMENT

INSERT INTO `[database_prefix]section` (`section_id`, `name`, `name_translation`, `discription`, `discr_translation`, `default_perms`, `section_name`, `section_path`, `error_message`, `data_count`) VALUES
(10001, 'menu_link_start', '_perm_name_menu_link_start', 'Anzeigen des Start-Links im Menu', '_perm_disc_menu_link_start', 1, '', '/inc/layout.php', 0, 0),
(10004, 'menu_link_myprofile', '_perm_name_menu_link_myprofile', 'Anzeigen des Mein Profil-Links im Menu', '_perm_disc_menu_link_myprofile', 1, '', '/inc/layout.php', 0, 0),
(10007, 'menu_link_servers', '_perm_name_menu_link_servers', 'Anzeigen des Server-Links im Menu', '_perm_disc_menu_link_servers', 1, '', '/inc/layout.php', 0, 0),
(10010, 'menu_link_channelviewer', '_perm_name_menu_link_channelviewer', 'Anzeigen des Channelviewer-Links im Menu', '_perm_disc_menu_link_channelviewer', 1, '', '/inc/layout.php', 0, 0),
(10013, 'menu_link_user', '_perm_name_menu_link_user', 'Anzeigen des User-Links im Menu', '_perm_disc_menu_link_user', 1, '', '/inc/layout.php', 0, 0),
(10016, 'menu_link_admin', '_perm_name_menu_link_admin', 'Anzeigen des Admin-Links im Menu', '_perm_disc_menu_link_admin', 1, '', '/inc/layout.php', 0, 0),
(10019, 'menu_link_create', '_perm_name_menu_link_create', 'Anzeigen des Erstellen-Links im Menu', '_perm_disc_menu_link_create', 1, '', '/inc/layout.php', 0, 0),
(10022, 'menu_link_request', '_perm_name_menu_link_request', 'Anzeigen des Konto beantragen-Links im Menu', '_perm_disc_menu_link_request', 1, '', '/inc/layout.php', 0, 0),
(10025, 'menu_link_log', '_perm_name_menu_link_log', 'Anzeigen des System Log-Links im Menu', '_perm_disc_menu_link_log', 1, '', '/inc/layout.php', 0, 0),
(10026, 'menu_link_email', '_perm_name_menu_link_email', 'Anzeigen des E-Mail Links im Menu', '_perm_disc_menu_link_email', 1, '', '/inc/layout.php', 0, 0),
(10028, 'menu_link_permissions', '_perm_name_menu_link_permissions', 'Anzeigen des Berechtigungen-Links im Menu', '_perm_disc_menu_link_permissions', 0, '', '/inc/layout.php', 0, 0),
(10031, 'menu_link_settings', '_perm_name_menu_link_settings', 'Anzeigen des Einstellungen-Links im Menu', '_perm_disc_menu_link_settings', 1, '', '/inc/layout.php', 0, 0),
(10034, 'menu_link_logout', '_perm_name_menu_link_logout', 'Anzeigen des Logout-Links im Menu', '_perm_disc_menu_link_logout', 1, '', '/inc/layout.php', 0, 0),
(11001, 'show_server', '_perm_name_show_server', 'Anzeiger der Server Details Seite', '_perm_disc_show_server', 1, 'show_server', '/server/index.php', 1, 1),
(11002, 'list_server', '_perm_name_list_server', 'Listenanzeige virtuelle Server', '_perm_disc_list_server', 1, 'list_server', '/server/index.php', 1, 1),
(11005, 'create_server', '_perm_name_create_server', 'virtuelle Server erstellen', '_perm_disc_create_server', 0, 'create_server', '/server/index.php', 1, 1),
(11006, 'edit_server', '_perm_name_edit_server', 'virtuellen Server editieren', '_perm_disc_edit_server', 1, 'edit_server', '/server/index.php', 1, 1),
(11007, 'delete_server', '_perm_name_delete_server', 'virtuellen Server editieren', '_perm_disc_delete_server', 0, 'delete_server', '/server/index.php', 1, 1),
(11020, 'server_start', '_perm_name_server_start', 'virtuellen Server starten', '_perm_disc_server_start', 1, 'start_virtual_server', '/server/index.php', 1, 1),
(11021, 'server_stop', '_perm_name_server_stop', 'virtuellen Server stoppen', '_perm_disc_server_stop', 1, 'stop_virtual_server', '/server/index.php', 1, 1),
(11022, 'server_restart', '_perm_name_server_restart', 'virtuellen Server neu starten', '_perm_disc_server_restart', 1, 'restart_virtual_server', '/server/index.php', 1, 1),
(12001, 'server_conf_name', '_perm_name_server_conf_name', 'Serverconfig ändern\r\nName', '_perm_disc_server_conf_name', 1, 'edit_server', '/server/index.php', 0, 0),
(12002, 'server_conf_guarantor', '_perm_name_server_conf_guarantor', 'Serverconfig ändern guarantor', '_perm_disc_server_conf_guarantor', 1, 'edit_server', '/server/index.php', 0, 0),
(12003, 'server_conf_payed_until', '_perm_name_server_conf_payed_until', 'Serverconfig ändern \r\nBezahlt bis', '_perm_disc_server_conf_payed_until', 0, 'edit_server', '/server/index.php', 0, 0),
(12004, 'server_conf_users', '_perm_name_server_conf_users', 'Serverconfig ändern\r\nmax. User', '_perm_disc_server_conf_users', 0, 'edit_server', '/server/index.php', 0, 0),
(12005, 'server_conf_port', '_perm_name_server_conf_port', 'Serverconfig ändern\r\nPort', '_perm_disc_server_conf_port', 0, 'edit_server', '/server/index.php', 0, 0),
(12006, 'server_conf_password', '_perm_name_server_conf_password', 'Serverconfig ändern\r\nPasswort', '_perm_disc_server_conf_password', 1, 'edit_server', '/server/index.php', 0, 0),
(12007, 'server_conf_timeout', '_perm_name_server_conf_timeout', 'Serverconfig ändern\r\ntimeout', '_perm_disc_server_conf_timeout', 1, 'edit_server', '/server/index.php', 0, 0),
(12008, 'server_conf_channelname', '_perm_name_server_conf_channelname', 'Serverconfig ändern\r\nchannelname', '_perm_disc_server_conf_channelname', 1, 'edit_server', '/server/index.php', 0, 0),
(12009, 'server_conf_username', '_perm_name_server_conf_username', 'Serverconfig ändern\r\nusername', '_perm_disc_server_conf_username', 1, 'edit_server', '/server/index.php', 0, 0),
(12010, 'server_conf_defaultchannel', '_perm_name_server_conf_defaultchannel', 'Serverconfig ändern\r\ndefaultchannel', '_perm_disc_server_conf_defaultchannel', 1, 'edit_server', '/server/index.php', 0, 0),
(12011, 'server_conf_registerHostname', '_perm_name_server_conf_registerHostname', 'Serverconfig ändern\r\nregisterHostname', '_perm_disc_server_conf_registerHostname', 1, 'edit_server', '/server/index.php', 0, 0),
(12012, 'server_conf_registerName', '_perm_name_server_conf_registerName', 'Serverconfig ändern\r\nregisterName', '_perm_disc_server_conf_registerName', 1, 'edit_server', '/server/index.php', 0, 0),
(12013, 'server_conf_registerPassword', '_perm_name_server_conf_registerPassword', 'Serverconfig ändern registerPassword', '_perm_disc_server_conf_registerPassword', 1, 'edit_server', '/server/index.php', 0, 0),
(12014, 'server_conf_registerUrl', '_perm_name_server_conf_registerUrl', 'Serverconfig ändern registerUrl', '_perm_disc_server_conf_registerUrl', 1, 'edit_server', '/server/index.php', 0, 0),
(12015, 'server_conf_bandwidth', '_perm_name_server_conf_bandwidth', 'Serverconfig ändern bandwidth', '_perm_disc_server_conf_bandwidth', 1, 'edit_server', '/server/index.php', 0, 0),
(12016, 'server_conf_imagemessagelength', '_perm_name_server_conf_imagemessagelength', 'Serverconfig ändern imagemessagelength', '_perm_disc_server_conf_imagemessagelength', 1, 'edit_server', '/server/index.php', 0, 0),
(12017, 'server_conf_textmessagelength', '_perm_name_server_conf_textmessagelength', 'Serverconfig ändern textmessagelength', '_perm_disc_server_conf_textmessagelength', 1, 'edit_server', '/server/index.php', 0, 0),
(12018, 'server_conf_usersperchannel', '_perm_name_server_conf_usersperchannel', 'Serverconfig ändern usersperchannel', '_perm_disc_server_conf_usersperchannel', 1, 'edit_server', '/server/index.php', 0, 0),
(12019, 'server_conf_certrequired', '_perm_name_server_conf_certrequired', 'Serverconfig ändern certrequired', '_perm_disc_server_conf_certrequired', 1, 'edit_server', '/server/index.php', 0, 0),
(12020, 'server_conf_obfuscate', '_perm_name_server_conf_obfuscate', 'Serverconfig ändern obfuscate', '_perm_disc_server_conf_obfuscate', 1, 'edit_server', '/server/index.php', 0, 0),
(12021, 'server_conf_rememberchannel', '_perm_name_server_conf_rememberchannel', 'Serverconfig ändern rememberchannel', '_perm_disc_server_conf_rememberchannel', 1, 'edit_server', '/server/index.php', 0, 0),
(12022, 'server_conf_allowhtml', '_perm_name_server_conf_allowhtml', 'Serverconfig ändern allowhtml', '_perm_disc_server_conf_allowhtml', 1, 'edit_server', '/server/index.php', 0, 0),
(12023, 'server_conf_allowping', '_perm_name_server_conf_allowping', 'Serverconfig ändern allowping', '_perm_disc_server_conf_allowping', 1, 'edit_server', '/server/index.php', 0, 0),
(12024, 'server_conf_welcometext', '_perm_name_server_conf_welcometext', 'Serverconfig ändern welcometext', '_perm_disc_server_conf_welcometext', 1, 'edit_server', '/server/index.php', 0, 0),
(12025, 'server_conf_discription', '_perm_name_server_conf_discription', 'Serverconfig ändern discription', '_perm_disc_server_conf_discription', 0, 'edit_server', '/server/index.php', 0, 0),
(12026, 'server_conf_registerLocation', '_perm_name_server_conf_registerLocation', 'Serverconfig ändern registerLocation', '_perm_disc_server_conf_registerLocation', 1, 'edit_server', '/server/index.php', 0, 0),
(12027, 'server_conf_sslca', '_perm_name_server_conf_sslca', 'Serverconfig ändern sslca', '_perm_disc_server_conf_sslca', 1, 'edit_server', '/server/index.php', 0, 0),
(12028, 'server_conf_sslcert', '_perm_name_server_conf_sslcert', 'Serverconfig ändern sslcert', '_perm_disc_server_conf_sslcert', 1, 'edit_server', '/server/index.php', 0, 0),
(12029, 'server_conf_sslkey', '_perm_name_server_conf_sslkey', 'Serverconfig ändern sslkey', '_perm_disc_server_conf_sslkey', 1, 'edit_server', '/server/index.php', 0, 0),
(12030, 'server_conf_sslpassphrase', '_perm_name_server_conf_sslpassphrase', 'Serverconfig ändern sslpassphrase', '_perm_disc_server_conf_sslpassphrase', 1, 'edit_server', '/server/index.php', 0, 0),
(12031, 'server_conf_channelnestinglimit', '_perm_name_server_conf_channelnestinglimit', 'Serverconfig ändern channelnestinglimit', '_perm_disc_server_conf_channelnestinglimit', 1, 'edit_server', '/server/index.php', 0, 0),
(12032, 'server_conf_opusthreshold', '_perm_name_server_conf_opusthreshold', 'Serverconfig ändern opusthreshold', '_perm_disc_server_conf_opusthreshold', 1, 'edit_server', '/server/index.php', 0, 0),
(12033, 'server_conf_suggestpositional', '_perm_name_server_conf_suggestpositional', 'Serverconfig ändern suggestpositional', '_perm_disc_server_conf_suggestpositional', 1, 'edit_server', '/server/index.php', 0, 0),
(12034, 'server_conf_suggestpushtotalk', '_perm_name_server_conf_suggestpushtotalk', 'Serverconfig ändern suggestpushtotalk', '_perm_disc_server_conf_suggestpushtotalk', 1, 'edit_server', '/server/index.php', 0, 0),
(12035, 'server_conf_suggestversion', '_perm_name_server_conf_suggestversion', 'Serverconfig ändern suggestversion', '_perm_disc_server_conf_suggestversion', 1, 'edit_server', '/server/index.php', 0, 0),
(12036, 'server_conf_sendversion', '_perm_name_server_conf_sendversion', 'Serverconfig ändern sendversion', '_perm_disc_server_conf_sendversion', 1, 'edit_server', '/server/index.php', 0, 0),
(12037, 'server_conf_bonjour', '_perm_name_server_conf_bonjour', 'Serverconfig ändern bonjour', '_perm_disc_server_conf_bonjour', 1, 'edit_server', '/server/index.php', 0, 0),
(13001, 'view_overview', '_perm_name_view_overview', 'Übersichtsseite Channelviewer Anzeigen', '_perm_disc_view_overview', 1, 'default', '/view/index.php', 1, 1),
(13002, 'view_channelviewer', '_perm_name_view_channelviewer', 'Channelviewer eines Servers anzeigen', '_perm_disc_view_channelviewer', 1, 'channelviewer', '/view/index.php', 1, 1),
(13003, 'include_channelviewer', '_perm_name_include_channelviewer', 'Berechtigung um Channelviewer extern einbinden anzuzeigen im MAP', '_perm_disc_include_channelviewer', 1, 'include', '/view/index.php', 1, 1),
(13004, 'settings_channelviewer', '_perm_name_settings_channelviewer', 'Berechtigung um die Einstellungen des externen Channelviewers zu bearbeiten', '_perm_disc_settings_channelviewer', 1, 'settings', '/view/index.php', 1, 1),
(14002, 'list_user', '_perm_name_list_user', 'Lister der Server user anzeigen', '_perm_disc_list_user', 1, 'show_users', '/user/index.php', 1, 1),
(14005, 'create_user', '_perm_name_create_user', 'Server User registieren/erstelen', '_perm_disc_create_user', 1, 'create_server_user', '/user/index.php', 1, 1),
(14006, 'edit_user', '_perm_name_edit_user', 'User editieren', '_perm_disc_edit_user', 1, 'edit_user', '/user/index.php', 1, 1),
(14007, 'delete_user', '_perm_name_delete_user', 'User löschen bzw. registrierung aufheben', '_perm_disc_delete_user', 1, 'delete_user', '/user/index.php', 1, 1),
(14011, 'mute_user', '_perm_name_mute_user', 'User auf dem Server Stumm stellen', '_perm_disc_mute_user', 1, 'mute_user', '/user/index.php', 1, 1),
(14012, 'deaf_user', '_perm_name_deaf_user', 'User auf dem Server Taub stellen', '_perm_disc_deaf_user', 1, 'deaf_user', '/user/index.php', 1, 1),
(14013, 'message_to_user', '_perm_name_message_to_user', 'Nachricht an User auf dem Server schicken', '_perm_disc_message_to_user', 1, 'message_to_user', '/user/index.php', 1, 1),
(14014, 'kick_user', '_perm_name_kick_user', 'User auf dem Server kicken', '_perm_disc_kick_user', 1, 'kick_user_default_db', '/user/index.php', 1, 1),
(17001, 'profile_admin', '_perm_name_profile_admin', 'Admin Profil anzeigen', '_perm_disc_profile_admin', 1, 'profile', '/admin/index.php', 1, 1),
(17002, 'list_admin', '_perm_name_list_admin', 'zeige Liste der Admins an', '_perm_disc_list_admin', 1, 'default', '/admin/index.php', 1, 1),
(17005, 'create_admin', '_perm_name_create_admin', 'Admin erstellen', '_perm_disc_create_admin', 1, 'create_admin', '/admin/index.php', 1, 1),
(17006, 'edit_admin', '_perm_name_edit_admin', 'Admin editieren', '_perm_disc_edit_admin', 1, 'edit_admin', '/admin/index.php', 1, 1),
(17007, 'delete_admin', '_perm_name_delete_admin', 'Admin löschen', '_perm_disc_delete_admin', 0, 'delete_admin', '/admin/index.php', 1, 1),
(17020, 'lock_admin', '_perm_name_lock_admin', 'Admin Sperren/Entsperren', '_perm_disc_lock_admin', 1, 'lock_admin', '/admin/index.php', 1, 1),
(17021, 'avatar_admin', '_perm_name_avatar_admin', '', '_perm_disc_avatar_admin', 1, 'avatar', '/admin/index.php', 1, 1),
(18001, 'edit_admin_name', '_perm_name_edit_admin_name', 'Admin Profil - Loginname ändern', '_perm_disc_edit_admin_name', 0, 'edit_admin', '/admin/index.php', 0, 0),
(18002, 'edit_admin_pass', '_perm_name_edit_admin_pass', 'Admin Profil - Passwort ändern', '_perm_disc_edit_admin_pass', 1, 'edit_admin', '/admin/index.php', 0, 0),
(18003, 'edit_admin_email', '_perm_name_edit_admin_email', 'Admin Profil - E-Mail ändern', '_perm_disc_edit_admin_email', 1, 'edit_admin', '/admin/index.php', 0, 0),
(18004, 'edit_admin_clantag', '_perm_name_edit_admin_clantag', 'Admin Profil - Clantag ändern', '_perm_disc_edit_admin_clantag', 1, 'edit_admin', '/admin/index.php', 0, 0),
(18005, 'edit_admin_username', '_perm_name_edit_admin_username', 'Admin Profil - Benutzernamen ändern', '_perm_disc_edit_admin_username', 1, 'edit_admin', '/admin/index.php', 0, 0),
(18006, 'edit_admin_type_id', '_perm_name_edit_admin_type_id', 'Admin Profil - Kontoart ändern', '_perm_disc_edit_admin_type_id', 0, 'edit_admin', '/admin/index.php', 0, 0),
(18007, 'edit_admin_group_id', '_perm_name_edit_admin_group_id', 'Admin Profil - Berechtigungsgruppe zuweisen', '_perm_disc_edit_admin_group_id', 0, 'edit_admin', '/admin/index.php', 0, 0),
(18008, 'edit_admin_server', '_perm_name_edit_admin_server', 'Admin Profil - Server zuweisen', '_perm_disc_edit_admin_server', 0, 'edit_admin', '/admin/index.php', 0, 0),
(18009, 'edit_admin_language', '_perm_name_edit_admin_language', 'Admin Profil - Sprache editieren', '_perm_disc_edit_admin_language', 1, 'edit_admin', '/admin/index.php', 0, 0),
(18010, 'edit_admin_template', '_perm_name_edit_admin_template', 'Admin Profil - Template editieren', '_perm_disc_edit_admin_template', 1, 'edit_admin', '/admin/index.php', 0, 0),
(18011, 'edit_admin_coockie', '_perm_name_edit_admin_coockie', 'Admin Profil - Coockies bearbeiten', '_perm_disc_edit_admin_coockie', 1, 'edit_admin', '/admin/index.php', 0, 0),
(18012, 'edit_admin_customer_id', '_perm_name_edit_admin_customer_id', 'Admin Profil - Kundennummer zuweisen', '_perm_disc_edit_admin_customer_id', 0, 'edit_admin', '/admin/index.php', 0, 0),
(18013, 'edit_admin_icq', '_perm_name_edit_admin_icq', 'Admin Profil - ICQ Nummer ändern', '_perm_disc_edit_admin_icq', 1, 'edit_admin', '/admin/index.php', 0, 0),
(18014, 'edit_admin_phone', '_perm_name_edit_admin_phone', 'Admin Profil - Telefonnummer ändern', '_perm_disc_edit_admin_phone', 1, 'edit_admin', '/admin/index.php', 0, 0),
(18015, 'edit_admin_street', '_perm_name_edit_admin_street', 'Admin Profil - Strasse ändern', '_perm_disc_edit_admin_street', 1, 'edit_admin', '/admin/index.php', 0, 0),
(18016, 'edit_admin_postalcode', '_perm_name_edit_admin_postalcode', 'Admin Profil - Postleizahl ändern', '_perm_disc_edit_admin_postalcode', 1, 'edit_admin', '/admin/index.php', 0, 0),
(18017, 'edit_admin_city', '_perm_name_edit_admin_city', 'Admin Profil - Ort ändern', '_perm_disc_edit_admin_city', 1, 'edit_admin', '/admin/index.php', 0, 0),
(18018, 'edit_admin_country', '_perm_name_edit_admin_country', 'Admin Profil - Land ändern', '_perm_disc_edit_admin_country', 1, 'edit_admin', '/admin/index.php', 0, 0),
(18019, 'edit_admin_discr', '_perm_name_edit_admin_discr', 'Admin Profil - Beschreibung ändern', '_perm_disc_edit_admin_discr', 1, 'edit_admin', '/admin/index.php', 0, 0),
(19001, 'list_accounts', '_perm_name_list_accounts', 'Listenanzeige beantragte Konten', '_perm_disc_list_accounts', 1, 'list_accounts', '/request/index.php', 1, 1),
(19006, 'edit_account', '_perm_name_edit_account', 'Beantragten Account editieren', '_perm_disc_edit_account', 1, 'edit_account', '/request/index.php', 1, 1),
(19007, 'delete_account', '_perm_name_delete_account', 'Beantragte Konten ablehnen', '_perm_disc_delete_account', 1, 'delete_account', '/request/index.php', 1, 1),
(19008, 'activate_account', '_perm_name_activate_account', 'Beantragte Konten aktivieren', '_perm_disc_activate_account', 1, 'activate_account', '/request/index.php', 1, 1),
(20001, 'log_overview', '_perm_name_log_overview', 'Startseite des Logging Bereichs', '_perm_disc_log_overview', 1, 'default', '/log/index.php', 1, 1),
(20002, 'show_log', '_perm_name_show_log', 'Zeige Logs für einen Server an.', '_perm_disc_show_log', 1, 'show_log', '/log/index.php', 1, 1),
(20003, 'show_log_all', '_perm_name_show_log_all', 'Zeige Alle Logs an, auch globale Logs', '_perm_disc_show_log_all', 1, 'show_log', '/log/index.php', 1, 1),
(20004, 'delete_log_db', '_perm_name_delete_log_db', 'Logs Löschen', '_perm_disc_delete_log_db', 0, 'delete_log_db', '/log/index.php', 1, 1),
(25001, 'perm_start_page', '_perm_name_perm_start_page', 'Startseite für Berechtigungen. Hier kann gewählt werden, was für eine Aktion als nächstes durchgeführt werden soll.', '_perm_disc_perm_start_page', 1, 'default', '/permissions/index.php', 1, 1),
(25002, 'perm_list_group', '_perm_name_perm_list_group', 'Listenanzeige der Berechtigungs-Gruppen', '_perm_disc_perm_list_group', 1, 'perm_list_group', '/permissions/index.php', 1, 1),
(25003, 'perm_create_group', '_perm_name_perm_create_group', 'Berechtigungsgruppe erstellen', '_perm_disc_perm_create_group', 0, 'create_group', '/permissions/index.php', 1, 1),
(25004, 'perm_edit_group', '_perm_name_perm_edit_group', 'Berechtigungsgruppe editieren', '_perm_disc_perm_edit_group', 0, 'edit_group', '/permissions/index.php', 1, 1),
(25005, 'perm_delete_group', '_perm_name_perm_delete_group', 'Berechtigungsgruppe löschen', '_perm_disc_perm_delete_group', 0, 'delete_group', '/permissions/index.php', 1, 1),
(25006, 'perm_recursive_rigths', '_perm_name_perm_recursive_rigths', 'Diese Regel besagt, dass der User nicht mehr rechte vergeben kann(beim erstellen oder editieren einer Gruppe) als dass er bereits jetzt hat. Wenn true=>rechte werden geerbt und können nicht >= vorhandene vergeben werden. Wenn false(0)=>rechte können zu 100% vergeben werden.', '_perm_disc_perm_recursive_rigths', 1, '', '/permissions/index.php', 0, 0),
(25012, 'perm_list_admin', '_perm_name_perm_list_admin', 'Listenanzeige der Berechtigungen einzelner Admin', '_perm_disc_perm_list_admin', 1, 'list_admin', '/permissions/index.php', 1, 1),
(25014, 'perm_edit_admin', '_perm_name_perm_edit_admin', 'Admin Berechtigungen editieren', '_perm_disc_perm_edit_admin', 1, 'edit_admin', '/permissions/index.php', 1, 1),
(35001, 'email_settings_header', '_perm_name_email_settings_header', 'E-Mail: Header bearbeiten', '_perm_disc_email_settings_header', 0, 'email_settings_header', '/email/index.php', 1, 1),
(35002, 'email_settings_footer', '_perm_name_email_settings_footer', 'E-Mail: Footer bearbeiten', '_perm_disc_email_settings_footer', 0, 'email_settings_footer', '/email/index.php', 1, 1),
(35003, 'email_list_mails', '_perm_name_email_list_mails', 'E-Mail: Items anzeigen', '_perm_disc_email_list_mails', 0, 'default', '/email/index.php', 1, 1),
(35004, 'email_edit_mails', '_perm_name_email_edit_mails', 'E-Mail: Items bearbeiten', '_perm_disc_email_edit_mails', 0, 'edit_mail', '/email/index.php', 1, 1),
(35005, 'email_send_mails', '_perm_name_email_send_mails', 'E-Mail: Items erneut senden', '_perm_disc_email_send_mails', 0, 'send_mail', '/email/index.php', 1, 1),
(35006, 'email_delete_mails', '_perm_name_email_delete_mails', 'E-Mail: Items löschen', '_perm_disc_email_delete_mails', 0, 'delete_mail', '/email/index.php', 1, 1),
(35007, 'email_list_templates', '_perm_name_email_list_templates', 'E-Mail: Templates anzeigen', '_perm_disc_email_list_templates', 0, 'list_templates', '/email/index.php', 1, 1),
(35008, 'email_edit_templates', '_perm_name_email_edit_templates', 'E-Mail: Templates bearbeiten', '_perm_disc_email_edit_templates', 0, 'edit_template', '/email/index.php', 1, 1),
(35009, 'email_lock_templates', '_perm_name_email_lock_templates', 'E-Mail: Templates sperren', '_perm_disc_email_lock_templates', 0, 'lock_template', '/email/index.php', 1, 1),
(35010, 'email_mass_user', '_perm_name_email_mass_user', 'Sende Massenmail an Server User eines Servers', '_perm_disc_email_mass_user', 1, 'mass_mail_server', '/server/index.php', 1, 1),
(35011, 'email_mass_customer', '_perm_name_email_mass_customer', 'Sende Massenmail an Kunden eines Servers', '_perm_disc_email_mass_customer', 1, 'admin_mail_server', '/server/index.php', 1, 1),
(35012, 'email_mass_reseller', '_perm_name_email_mass_reseller', 'Sende Massenmail an Reseller ds Servers', '_perm_disc_email_mass_reseller', 1, 'map_admin_mail_server', '/server/index.php', 1, 1),
(93001, 'settings_show_set1', '_perm_name_settings_show_set1', 'Globale MAP Einstellungen anzeigen (Allgemein)', '_perm_disc_settings_show_set1', 1, 'default', '/settings/index.php', 0, 1),
(93002, 'settings_show_set2', '_perm_name_settings_show_set2', 'Globale MAP-Einstelllungen anzeigen (E-Mail)', '_perm_disc_settings_show_set2', 1, 'settings_show', '/settings/index.php', 0, 1),
(93003, 'settings_show_set3', '_perm_name_settings_show_set3', 'Globale MAP Einstellungen anzeigen (Konto beantragen)', '_perm_disc_settings_show_set3', 1, 'settings_show', '/settings/index.php', 0, 1),
(93004, 'settings_show_set4', '_perm_name_settings_show_set4', 'Globale MAP Einstellungen anzeigen (Schnittstellenkonfiguration)', '_perm_disc_settings_show_set4', 1, 'settings_show', '/settings/index.php', 0, 1),
(93005, 'settings_show_set5', '_perm_name_settings_show_set5', 'Globale MAP Einstellungen anzeigen (Log-Funktion)', '_perm_disc_settings_show_set5', 1, 'settings_show', '/settings/index.php', 0, 1),
(93006, 'settings_show_set6', '_perm_name_settings_show_set6', 'Globale MAP Einstellungen anzeigen (Passwort vergessen)', '_perm_disc_settings_show_set6', 1, 'settings_show', '/settings/index.php', 0, 1),
(93007, 'settings_show_set7', '_perm_name_settings_show_set7', 'Globale MAP Einstellungen anzeigen (Über)', '_perm_disc_settings_show_set7', 1, 'settings_show', '/settings/index.php', 0, 1),
(93021, 'settings_db_set1', '_perm_name_settings_db_set1', 'Globale MAP Einstellungen editieren (Allgemein)', '_perm_disc_settings_db_set1', 0, 'settings_db', '/settings/index.php', 0, 1),
(93022, 'settings_db_set2', '_perm_name_settings_db_set2', 'Globale MAP Einstellungen editieren (E-Mail)', '_perm_disc_settings_db_set2', 0, 'settings_db', '/settings/index.php', 0, 1),
(93023, 'settings_db_set3', '_perm_name_settings_db_set3', 'Globale MAP Einstellungen editieren (Konto beantragen)', '_perm_disc_settings_db_set3', 0, 'settings_db', '/settings/index.php', 0, 1),
(93024, 'settings_db_set4', '_perm_name_settings_db_set4', 'Globale MAP Einstellungen editieren (Schnittstellenkonfiguration)', '_perm_disc_settings_db_set4', 0, 'settings_db', '/settings/index.php', 0, 1),
(93025, 'settings_db_set5', '_perm_name_settings_db_set5', 'Globale MAP Einstellungen anzeigen (Log-Funktion)', '_perm_disc_settings_db_set5', 0, 'settings_db', '/settings/index.php', 0, 1),
(93026, 'settings_db_set6', '_perm_name_settings_db_set6', 'Globale MAP Einstellungen anzeigen (Passwort vergessen)', '_perm_disc_settings_db_set6', 0, 'settings_db', '/settings/index.php', 0, 1);

-- BEGINN NEW STATEMENT

CREATE TABLE IF NOT EXISTS `[database_prefix]section_data` (
  `id` int(9) NOT NULL AUTO_INCREMENT,
  `section_id` varchar(9) collate utf8_unicode_ci NOT NULL,
  `user_id` int(9) NOT NULL,
  `access_count` int(9) NOT NULL,
  `ip` varchar(15) collate utf8_unicode_ci NOT NULL,
  `date` timestamp NOT NULL default CURRENT_TIMESTAMP,
  KEY `id` (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci PACK_KEYS=1 AUTO_INCREMENT=1 ;

-- BEGINN NEW STATEMENT

CREATE TABLE IF NOT EXISTS `[database_prefix]servers` (
  `server_id` int(9) NOT NULL COMMENT 'Server ID ist gleich der Original server_id von Murmur',
  `name` varchar(255) collate utf8_unicode_ci NOT NULL default 'Servername' COMMENT 'Name des Servers',
  `discription` text collate utf8_unicode_ci NOT NULL COMMENT 'Beschreibung des Servers',
  `guarantor` int(9) NOT NULL default '1' COMMENT 'guarantor = user_id: Besagt welcher map Admin verantwortlich für diesen Server ist',
  `started` datetime NOT NULL default '[aktdate]' COMMENT 'Wert besagt, seit wann der Server Online ist',
  `payed_until` datetime NOT NULL default '2015-12-31 23:59:00' COMMENT 'Zahlstatus, bis wann der server bezahlt ist, bzw. wann dieser offline geht.',
  `starts` int(9) NOT NULL default '0' COMMENT 'Zähler, wie oft der server gestartet wurde'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- BEGINN NEW STATEMENT

INSERT INTO `[database_prefix]servers` (`server_id`, `name`, `discription`, `guarantor`, `started`, `payed_until`, `starts`) VALUES
(1, 'Defaultserver', '<p>This Server stands in Default settings. Please edit!</p>', 1, '[aktdate]', '2015-12-31 23:59:59', 0);

-- BEGINN NEW STATEMENT

CREATE TABLE IF NOT EXISTS `[database_prefix]settings` (
  `id` int(9) NOT NULL AUTO_INCREMENT,
  `value_1` varchar(255) collate utf8_unicode_ci NOT NULL,
  `value_2` mediumtext collate utf8_unicode_ci default NULL,
  KEY `id` (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=47 ;

-- BEGINN NEW STATEMENT

INSERT INTO `[database_prefix]settings` (`id`, `value_1`, `value_2`) VALUES
(1, 'version_num', '[version_num]'),
(2, 'version_date', '[version_date]'),
(3, 'name_1', 'MAP'),
(4, 'authed', '1'),
(5, 'tpldir', '[template]'),
(6, 'language', '[language]'),
(7, 'copyrigth', '<a href="mailto:%73%75%70%70%6F%72%74%40%6D%75%6D%62%31%65%2E%64%65">&copy;2009-2013|by P.M.</a>'),
(8, 'show_version_pagetitle', '1'),
(15, 'install', '[aktdate]'),
(16, 'request_account', '1'),
(18, 'request_password', ''),
(19, 'request_pw_on', '0'),
(20, 'system', '[system]'),
(23, 'log_on', '1'),
(24, 'log_priority', '1'),
(25, 'log_show_priority', '3'),
(26, 'log_days', '14'),
(27, 'log_show_permissions', '1'),
(28, 'ice_host', '127.0.0.1'),
(29, 'ice_port', '6502'),
(30, 'ver_chk_on', '1'),
(31, 'request_access', '3'),
(32, 'operate_access', '1'),
(33, 'ice_secret', '[slice_secret]'),
(34, 'host', '[host]'),
(35, 'version_build', '[version_build]'),
(36, 'email_header', ''),
(37, 'email_footer', '<p>+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+</p>\r\n<p><em>Dies ist eine automatisch generierte E-Mail. Bitte nicht darauf Antworten!</em></p>\r\n<p><em>This is an automatically generated E-Mail. Please don&acute;t reply!<br /></em></p>\r\n<p><em><em>+-<em>+-<em>+-<em>+-<em>+-<em>+-<em>+-<em>+-<em>+-<em>+-<em>+-<em>+-<em>+-<em>+-<em>+-<em>+-<em>+-<em>+-<em>+-<em>+-<em>+-<em>+-<em>+-<em>+-<em>+-<em>+-<em>+-<em>+-<em>+-<em>+-<em>+-<em>+-<em>+-<em>+-</em></em></em></em></em></em></em></em></em></em></em></em></em></em></em></em></em></em></em></em></em></em></em></em></em></em></em></em></em></em></em></em></em></em>+-+-+-+-+-+-+</em></p>\r\n<p><em>Diese E-Mail wurde vom MAP - Mumb1e Admin Plugin generiert und versendet.</em></p>\r\n<p><em>This E-Mail was sent and generated by MAP - Mumb1e Admin Plugin.</em></p>\r\n<p><em>Powered by <a href="http://www.mumb1e.de/" title="Mumb1e.de">http://www.mumb1e.de/</a>.</em></p>\r\n<p><em>Inhalte vorbehalten.</em></p>\r\n<p><em>Content reserved.</em></p>'),
(38, 'email_subject_prefix', 'MAP | '),
(39, 'email_delete_history', '14'),
(40, 'email_type', 'mail'),
(41, 'email_host', ''),
(42, 'email_port', ''),
(43, 'email_username', ''),
(44, 'email_password', ''),
(45, 'GoogleReCaptchaPublicKey', ''),
(46, 'GoogleReCaptchaPrivateKey', ''),
(47, 'email_sender', '');

-- BEGINN NEW STATEMENT

CREATE TABLE IF NOT EXISTS `[database_prefix]user` (
  `user_id` int(9) NOT NULL AUTO_INCREMENT,
  `type_id` int(9) NOT NULL,
  `group_id` varchar(9) collate utf8_unicode_ci NOT NULL,
  `perm_id` varchar(9) collate utf8_unicode_ci NOT NULL,
  `customer_id` varchar(25) collate utf8_unicode_ci NOT NULL,
  `name` varchar(255) collate utf8_unicode_ci NOT NULL,
  `username` varchar(255) collate utf8_unicode_ci NOT NULL,
  `clantag` varchar(255) collate utf8_unicode_ci NOT NULL,
  `email` varchar(255) collate utf8_unicode_ci NOT NULL,
  `pw` varchar(128) collate utf8_unicode_ci NOT NULL,
  `logins` int(9) NOT NULL,
  `last_active` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  `lock` int(9) NOT NULL,
  `language` varchar(20) collate utf8_unicode_ci NOT NULL,
  `template` varchar(20) collate utf8_unicode_ci NOT NULL,
  `coockie` int(9) NOT NULL,
  `icq` varchar(11) collate utf8_unicode_ci NOT NULL,
  `discr` text collate utf8_unicode_ci NOT NULL,
  `phone` varchar(50) collate utf8_unicode_ci NOT NULL,
  `street` varchar(50) collate utf8_unicode_ci NOT NULL,
  `postalcode` varchar(8) collate utf8_unicode_ci NOT NULL,
  `city` varchar(50) collate utf8_unicode_ci NOT NULL,
  `country` varchar(50) collate utf8_unicode_ci NOT NULL,
  PRIMARY KEY  (`user_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

-- BEGINN NEW STATEMENT

INSERT INTO `[database_prefix]user` (`user_id`, `type_id`, `group_id`, `perm_id`, `customer_id`, `name`, `username`, `clantag`, `email`, `pw`, `logins`, `last_active`, `lock`, `language`, `template`, `coockie`, `icq`, `discr`, `phone`, `street`, `postalcode`, `city`, `country`) VALUES
(1, 1, '5bS48ceDP', '1s4lD7GLo', '', '[name]', '[username]', '[clantag]', '[email]', '[pw]', 0, '[aktdate]', 1, '[language]', '[template]', 86400, '', '', '', '', '', '', '');

-- BEGINN NEW STATEMENT

CREATE TABLE IF NOT EXISTS `[database_prefix]user_perm` (
  `perm_id` varchar(9) collate utf8_unicode_ci NOT NULL,
  `section_id` varchar(9) collate utf8_unicode_ci NOT NULL,
  `value` int(9) NOT NULL,
  `date` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='Indviduelle Userberechtigungen';

-- BEGINN NEW STATEMENT

INSERT INTO `[database_prefix]user_perm` (`perm_id`, `section_id`, `value`, `date`) VALUES
('1s4lD7GLo', '10001', 0, '[aktdate]'),
('1s4lD7GLo', '10004', 0, '[aktdate]'),
('1s4lD7GLo', '10007', 0, '[aktdate]'),
('1s4lD7GLo', '10010', 0, '[aktdate]'),
('1s4lD7GLo', '10013', 0, '[aktdate]'),
('1s4lD7GLo', '10016', 0, '[aktdate]'),
('1s4lD7GLo', '10019', 0, '[aktdate]'),
('1s4lD7GLo', '10022', 0, '[aktdate]'),
('1s4lD7GLo', '10025', 0, '[aktdate]'),
('1s4lD7GLo', '10026', 0, '[aktdate]'),
('1s4lD7GLo', '10028', 0, '[aktdate]'),
('1s4lD7GLo', '10031', 0, '[aktdate]'),
('1s4lD7GLo', '10034', 0, '[aktdate]'),
('1s4lD7GLo', '11001', 0, '[aktdate]'),
('1s4lD7GLo', '11002', 0, '[aktdate]'),
('1s4lD7GLo', '11005', 0, '[aktdate]'),
('1s4lD7GLo', '11006', 0, '[aktdate]'),
('1s4lD7GLo', '11007', 0, '[aktdate]'),
('1s4lD7GLo', '11020', 0, '[aktdate]'),
('1s4lD7GLo', '11021', 0, '[aktdate]'),
('1s4lD7GLo', '11022', 0, '[aktdate]'),
('1s4lD7GLo', '12001', 0, '[aktdate]'),
('1s4lD7GLo', '12002', 0, '[aktdate]'),
('1s4lD7GLo', '12003', 0, '[aktdate]'),
('1s4lD7GLo', '12004', 0, '[aktdate]'),
('1s4lD7GLo', '12005', 0, '[aktdate]'),
('1s4lD7GLo', '12006', 0, '[aktdate]'),
('1s4lD7GLo', '12007', 0, '[aktdate]'),
('1s4lD7GLo', '12008', 0, '[aktdate]'),
('1s4lD7GLo', '12009', 0, '[aktdate]'),
('1s4lD7GLo', '12010', 0, '[aktdate]'),
('1s4lD7GLo', '12011', 0, '[aktdate]'),
('1s4lD7GLo', '12012', 0, '[aktdate]'),
('1s4lD7GLo', '12013', 0, '[aktdate]'),
('1s4lD7GLo', '12014', 0, '[aktdate]'),
('1s4lD7GLo', '12015', 0, '[aktdate]'),
('1s4lD7GLo', '12016', 0, '[aktdate]'),
('1s4lD7GLo', '12017', 0, '[aktdate]'),
('1s4lD7GLo', '12018', 0, '[aktdate]'),
('1s4lD7GLo', '12019', 0, '[aktdate]'),
('1s4lD7GLo', '12020', 0, '[aktdate]'),
('1s4lD7GLo', '12021', 0, '[aktdate]'),
('1s4lD7GLo', '12022', 0, '[aktdate]'),
('1s4lD7GLo', '12023', 0, '[aktdate]'),
('1s4lD7GLo', '12024', 0, '[aktdate]'),
('1s4lD7GLo', '12025', 0, '[aktdate]'),
('1s4lD7GLo', '12026', 0, '[aktdate]'),
('1s4lD7GLo', '12027', 0, '[aktdate]'),
('1s4lD7GLo', '12028', 0, '[aktdate]'),
('1s4lD7GLo', '12029', 0, '[aktdate]'),
('1s4lD7GLo', '12030', 0, '[aktdate]'),
('1s4lD7GLo', '12031', 0, '[aktdate]'),
('1s4lD7GLo', '12032', 0, '[aktdate]'),
('1s4lD7GLo', '12033', 0, '[aktdate]'),
('1s4lD7GLo', '12034', 0, '[aktdate]'),
('1s4lD7GLo', '12035', 0, '[aktdate]'),
('1s4lD7GLo', '12036', 0, '[aktdate]'),
('1s4lD7GLo', '12037', 0, '[aktdate]'),
('1s4lD7GLo', '13001', 0, '[aktdate]'),
('1s4lD7GLo', '13002', 0, '[aktdate]'),
('1s4lD7GLo', '13003', 0, '[aktdate]'),
('1s4lD7GLo', '13004', 0, '[aktdate]'),
('1s4lD7GLo', '14002', 0, '[aktdate]'),
('1s4lD7GLo', '14005', 0, '[aktdate]'),
('1s4lD7GLo', '14006', 0, '[aktdate]'),
('1s4lD7GLo', '14007', 0, '[aktdate]'),
('1s4lD7GLo', '14011', 0, '[aktdate]'),
('1s4lD7GLo', '14012', 0, '[aktdate]'),
('1s4lD7GLo', '14013', 0, '[aktdate]'),
('1s4lD7GLo', '14014', 0, '[aktdate]'),
('1s4lD7GLo', '17001', 0, '[aktdate]'),
('1s4lD7GLo', '17002', 0, '[aktdate]'),
('1s4lD7GLo', '17005', 0, '[aktdate]'),
('1s4lD7GLo', '17006', 0, '[aktdate]'),
('1s4lD7GLo', '17007', 0, '[aktdate]'),
('1s4lD7GLo', '17020', 0, '[aktdate]'),
('1s4lD7GLo', '17021', 0, '[aktdate]'),
('1s4lD7GLo', '18001', 0, '[aktdate]'),
('1s4lD7GLo', '18002', 0, '[aktdate]'),
('1s4lD7GLo', '18003', 0, '[aktdate]'),
('1s4lD7GLo', '18004', 0, '[aktdate]'),
('1s4lD7GLo', '18005', 0, '[aktdate]'),
('1s4lD7GLo', '18006', 0, '[aktdate]'),
('1s4lD7GLo', '18007', 0, '[aktdate]'),
('1s4lD7GLo', '18008', 0, '[aktdate]'),
('1s4lD7GLo', '18009', 0, '[aktdate]'),
('1s4lD7GLo', '18010', 0, '[aktdate]'),
('1s4lD7GLo', '18011', 0, '[aktdate]'),
('1s4lD7GLo', '18012', 0, '[aktdate]'),
('1s4lD7GLo', '18013', 0, '[aktdate]'),
('1s4lD7GLo', '18014', 0, '[aktdate]'),
('1s4lD7GLo', '18015', 0, '[aktdate]'),
('1s4lD7GLo', '18016', 0, '[aktdate]'),
('1s4lD7GLo', '18017', 0, '[aktdate]'),
('1s4lD7GLo', '18018', 0, '[aktdate]'),
('1s4lD7GLo', '18019', 0, '[aktdate]'),
('1s4lD7GLo', '19001', 0, '[aktdate]'),
('1s4lD7GLo', '19006', 0, '[aktdate]'),
('1s4lD7GLo', '19007', 0, '[aktdate]'),
('1s4lD7GLo', '19008', 0, '[aktdate]'),
('1s4lD7GLo', '20001', 0, '[aktdate]'),
('1s4lD7GLo', '20002', 0, '[aktdate]'),
('1s4lD7GLo', '20003', 0, '[aktdate]'),
('1s4lD7GLo', '20004', 0, '[aktdate]'),
('1s4lD7GLo', '25001', 0, '[aktdate]'),
('1s4lD7GLo', '25002', 0, '[aktdate]'),
('1s4lD7GLo', '25003', 0, '[aktdate]'),
('1s4lD7GLo', '25004', 0, '[aktdate]'),
('1s4lD7GLo', '25005', 0, '[aktdate]'),
('1s4lD7GLo', '25006', 0, '[aktdate]'),
('1s4lD7GLo', '25012', 0, '[aktdate]'),
('1s4lD7GLo', '25014', 0, '[aktdate]'),
('1s4lD7GLo', '35001', 0, '[aktdate]'),
('1s4lD7GLo', '35002', 0, '[aktdate]'),
('1s4lD7GLo', '35003', 0, '[aktdate]'),
('1s4lD7GLo', '35004', 0, '[aktdate]'),
('1s4lD7GLo', '35005', 0, '[aktdate]'),
('1s4lD7GLo', '35006', 0, '[aktdate]'),
('1s4lD7GLo', '35007', 0, '[aktdate]'),
('1s4lD7GLo', '35008', 0, '[aktdate]'),
('1s4lD7GLo', '35009', 0, '[aktdate]'),
('1s4lD7GLo', '35010', 0, '[aktdate]'),
('1s4lD7GLo', '35011', 0, '[aktdate]'),
('1s4lD7GLo', '35012', 0, '[aktdate]'),
('1s4lD7GLo', '93001', 0, '[aktdate]'),
('1s4lD7GLo', '93002', 0, '[aktdate]'),
('1s4lD7GLo', '93003', 0, '[aktdate]'),
('1s4lD7GLo', '93004', 0, '[aktdate]'),
('1s4lD7GLo', '93005', 0, '[aktdate]'),
('1s4lD7GLo', '93006', 0, '[aktdate]'),
('1s4lD7GLo', '93007', 0, '[aktdate]'),
('1s4lD7GLo', '93021', 0, '[aktdate]'),
('1s4lD7GLo', '93022', 0, '[aktdate]'),
('1s4lD7GLo', '93023', 0, '[aktdate]'),
('1s4lD7GLo', '93024', 0, '[aktdate]'),
('1s4lD7GLo', '93025', 0, '[aktdate]'),
('1s4lD7GLo', '93026', 0, '[aktdate]');

-- BEGINN NEW STATEMENT

CREATE TABLE IF NOT EXISTS `[database_prefix]user_servers` (
  `id` int(9) NOT NULL auto_increment,
  `user_id` int(9) NOT NULL,
  `server_id` int(9) NOT NULL,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

-- BEGINN NEW STATEMENT

INSERT INTO `[database_prefix]user_servers` (`id`, `user_id`, `server_id`) VALUES
(1, 1, 1);