#! /bin/bash

app=mumble_admin_plugin
domain=$1
path=$2
admin=$3
admin_email=$4
admin_pwd=$5
final_path=/var/www/$app

# Check if mumble is installed by checking conf file 
if [[ ! -f "/etc/mumble-server.ini" ]]; then
	echo "Mumble server is not installed !";
	exit 1;
fi

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a $app
if [[ ! $? -eq 0 ]]; then
	echo "Path of the domain is not available"
	exit 1
fi

# Check user
sudo yunohost user list --json | grep -q "\"username\": \"$admin\""
if [[ ! $? -eq 0 ]]; then
	echo "Error : the chosen admin user does not exist"
	exit 1
fi

# Check /var/www/$app path is available
if [ -f $final_path ]; then
	echo "This path already contains a folder"
	exit 1
fi

# Save app settings
sudo yunohost app setting $app domain -v "$domain"
sudo yunohost app setting $app admin -v "$admin"
sudo yunohost app setting $app final_path -v "$final_path"

sudo mkdir $final_path
sudo cp -R ../sources/* $final_path
# Set permissions
sudo chmod 775 -R $final_path
sudo chmod 777 -R $final_path/inc/{_mysql.php,uploads/avatars/}
sudo chmod 777 -R $final_path/install/install.php
sudo chmod 666 -R $final_path/index.php
sudo chown -hR www-data:www-data $final_path

sudo yunohost app addaccess $app -u $admin

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sed -i "s@ALIASTOCHANGE@$final_path/@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf

# Reload Nginx and regenerate SSOwat conf
sudo service nginx reload
sudo yunohost app setting $app skipped_uris -v "/"
sudo yunohost app ssowatconf

# Starting auto-configuration #

# Prepare mumble for ice
sudo apt-get update -qq > /dev/null 2>&1
sudo apt-get install -y php-zeroc-ice > /dev/null 2>&1
sudo nginx -s reload 
ice_pass=$(dd if=/dev/urandom bs=1 count=200 2> /dev/null | tr -c -d '[A-Za-z0-9]' | sed -n 's/\(.\{24\}\).*/\1/p')
mumble_conf="/etc/mumble-server.ini"
sudo sed -e '/dbus=/ s/^#*/#/' -i $mumble_conf
sudo sed -i "s/#ice=/ice=/g" $mumble_conf
sudo sed -i "s/icesecretwrite=.*/icesecretwrite=$ice_pass/g" $mumble_conf
sudo sed -i '/^#.* icesecretwrite= /s/^#//' $mumble_conf
# Generate random password
mysql_pass=$(dd if=/dev/urandom bs=1 count=200 2> /dev/null | tr -c -d '[A-Za-z0-9]' | sed -n 's/\(.\{24\}\).*/\1/p')

# Use 'mumble_map' as database name and user
db_user=mumble_map
# Initialize database and store mysql password for upgrade
sudo yunohost app initdb $db_user -p $mysql_pass
sudo yunohost app setting $app mysql_pass -v $mysql_pass

# send http POST values
curl -k -X POST \
  -H "Host: $domain" \
  --data-urlencode "mysql_host=127.0.0.1" \
  --data-urlencode "mysql_user=$db_user" \
  --data-urlencode "mysql_pass=$mysql_pass" \
  --data-urlencode "database_name=$db_user" \
  --data-urlencode "database_prefix=_map" \
  --data-urlencode "slice_secret=$ice_pass" \
  --data-urlencode "map_user_name=$admin" \
  --data-urlencode "map_user_email=$admin_email" \
  --data-urlencode "map_user_pwd_1=$admin_pwd" \
  --data-urlencode "map_user_pwd_2=$admin_pwd" \
  "https://127.0.0.1$path/install/install.php?section=save_preferences" > /dev/null 2>&1

# request installation
curl -k -X POST \
  -H "Host: $domain" \
  --data-urlencode "mysql_host=127.0.0.1" \
  --data-urlencode "mysql_user=$db_user" \
  --data-urlencode "mysql_pass=$mysql_pass" \
  --data-urlencode "database_name=$db_user" \
  --data-urlencode "database_prefix=_map" \
  --data-urlencode "slice_secret=$slice_secret" \
  --data-urlencode "map_user_name=$admin" \
  --data-urlencode "map_user_email=$admin_email" \
  --data-urlencode "map_user_pwd_1=$admin_pwd" \
  --data-urlencode "map_user_pwd_2=$admin_pwd" \
  "https://127.0.0.1$path/install/install.php?section=install" > /dev/null 2>&1

# removing install folder for security
 sudo rm -rf $final_path/install/
 sudo chmod 664 $final_path/index.php
 sudo chmod 660 $final_path/inc/_mysql.php

 sudo yunohost app setting $app skipped_uris -d
 sudo yunohost app ssowatconf