#! /bin/bash
app=mumble_admin_plugin
user=$(sudo yunohost app setting $app admin)
final_path=$(sudo yunohost app setting $app final_path)
domain=$(sudo yunohost app setting $app domain)

root_pwd=$(sudo cat /etc/yunohost/mysql)
db_user=mumble_map
db_name=mumble_map

# Suppression du dossier de map
sudo rm -rf $final_path
# Suppression de la config nginx de map
sudo rm -f /etc/nginx/conf.d/$domain.d/$app.conf

mysql -u root -p$root_pwd -e "DROP DATABASE $db_name ; DROP USER $db_user@localhost ;"

sudo service nginx reload
sudo yunohost app ssowatconf